```yaml
version: '3.8'

services:
  # Hadoop NameNode
  namenode:
    image: apache/hadoop:3.3.4
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - "9000:9000"
      - "9870:9870"
    env_file:
      - ./hadoop.env
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - sentiment_network

  # Hadoop DataNode
  datanode:
    image: apache/hadoop:3.3.4
    command: ["hdfs", "datanode"]
    ports:
      - "9864:9864"
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - sentiment_network
    depends_on:
      - namenode

  # Hive Metastore
  hive-metastore:
    image: apache/hive:3.1.3
    hostname: hive-metastore
    ports:
      - "9083:9083"
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: "-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=hive"
    depends_on:
      - postgres
    networks:
      - sentiment_network

  # HiveServer2
  hiveserver2:
    image: apache/hive:3.1.3
    hostname: hiveserver2
    ports:
      - "10000:10000"
      - "10002:10002"
    environment:
      SERVICE_NAME: hiveserver2
      SERVICE_OPTS: "-Dhive.metastore.uris=thrift://hive-metastore:9083"
      IS_RESUME: "true"
    depends_on:
      - hive-metastore
    networks:
      - sentiment_network

  # PostgreSQL for Hive Metastore
  postgres:
    image: postgres:13
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sentiment_network

  # Spark Master
  spark-master:
    image: bitnami/spark:3.4.0
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - sentiment_network

  # Spark Worker
  spark-worker:
    image: bitnami/spark:3.4.0
    hostname: spark-worker
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    networks:
      - sentiment_network

  # Sentiment Analysis App
  sentiment-app:
    build: .
    hostname: sentiment-app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./:/app
      - ./data:/app/data
    depends_on:
      - namenode
      - hiveserver2
      - spark-master
    networks:
      - sentiment_network

volumes:
  hadoop_namenode:
  hadoop_datanode:
  postgres_data:

networks:
  sentiment_network:
    driver: bridge